import SwiftUI
import SpecimenCore
import SpecimenTestKit

/// Developer-only: runs any stack pipeline end to end on a synthetic dataset (generated by SpecimenTestKit) through the same
/// StackProcessor, working-image format and final encoder used for real stacks. For imported image sets, use Import Stack.
struct DebugPipelineView: View {
    enum Scenario: String, CaseIterable, Identifiable { case focus = "Focus (8 planes)", lighting = "Lighting (4 positions)", combined = "Combined (4 × 3)"; var id: String { rawValue } }
    @State private var scenario: Scenario = .focus
    @State private var running = false
    @State private var log = ""
    @State private var result: UIImage?

    var body: some View {
        Form {
            Picker("Scenario", selection: $scenario) { ForEach(Scenario.allCases) { Text($0.rawValue).tag($0) } }
            Button(running ? "Running…" : "Run pipeline") { Task { await run() } }.disabled(running)
            if let result { Image(uiImage: result).resizable().scaledToFit() }
            Text(log).font(.system(size: 11, design: .monospaced))
        }.navigationTitle("Test pipelines")
    }

    /// Developer "frames": already-working `.scw` files, so the developer step is a plain copy.
    struct ScwCopyDeveloper: FrameDeveloper {
        func develop(source: URL, kind: FrameFileKind, to destination: URL) throws -> (width: Int, height: Int) {
            let f = try ScwFrame(url: source)
            let w = try ScwWriter(url: destination, width: f.width, height: f.height, colorSpace: f.colorSpace)
            for t in TileGrid(imageWidth: f.width, imageHeight: f.height, tileSize: 512, halo: 0).tiles { try w.write(region: t.core, image: try f.read(region: t.core)) }
            try w.finish()
            return (f.width, f.height)
        }
    }

    private func run() async {
        running = true; log = ""; result = nil
        let sc = scenario
        let t0 = Date()
        do {
            let (url, lines) = try await Task.detached(priority: .userInitiated) { () -> (URL, [String]) in
                let root = AppPaths.staging.appendingPathComponent("debug_\(UUID().uuidString.prefix(6))", isDirectory: true)
                defer { try? FileManager.default.removeItem(at: root) }
                let store = try TemporaryStackStore(root: root.appendingPathComponent("p"))
                var groups: [[RGBImage]]; var type: StackType
                switch sc {
                case .focus: type = .focus; groups = [SyntheticFocus.make(width: 1024, height: 768, frames: 8, seed: 3, noise: 0.003, jitter: true).frames]
                case .lighting: type = .lighting; groups = SyntheticLighting.standardScenario(width: 1024, height: 768).frames.map { [$0] }
                case .combined:
                    type = .combined
                    let focus = SyntheticFocus.make(width: 768, height: 576, frames: 4, seed: 9, noise: 0.002, breathing: 0).frames
                    groups = (0..<3).map { gi in focus.map { fr in
                        var lin = ColorMath.toLinear(fr)
                        let cx = [0.25, 0.7, 0.45][gi] * Double(fr.width), cy = [0.3, 0.35, 0.8][gi] * Double(fr.height), s = 0.07 * Double(fr.width)
                        for y in 0..<fr.height { for x in 0..<fr.width {
                            let a = Float(3.5 * exp(-((Double(x) - cx) * (Double(x) - cx) + (Double(y) - cy) * (Double(y) - cy)) / (2 * s * s)))
                            lin.r[x, y] += a; lin.g[x, y] += a; lin.b[x, y] += a
                        }}
                        return ColorMath.toEncoded(lin).mapped { min(max($0, 0), 1) }
                    }}
                }
                var p = StackProject(type: type); p.quality = .high; try store.createProject(p)
                for (gi, imgs) in groups.enumerated() {
                    var g = FocusStackGroup(lightingPosition: type == .focus ? nil : gi)
                    for img in imgs {
                        let name = store.newFrameFileName(project: p, ext: "scw")
                        try ScwWriter.save(img, to: store.framesDirectory(p.id).appendingPathComponent(name))
                        var f = StackFrame(fileName: name, kind: .scw); f.lightingPosition = type == .focus ? nil : gi; g.frames.append(f)
                    }
                    p.groups.append(g)
                }
                p.status = .readyToProcess; try store.save(p)
                let services = ProcessingServices(developer: ScwCopyDeveloper(), encoder: FinalImageEncoder(), concurrency: { DeviceStatus.currentConcurrency() })
                let out = AppPaths.exports
                let r = try StackProcessor(store: store).process(projectID: p.id, outputDirectory: out, services: services)
                let keep = AppPaths.exports.appendingPathComponent("debug_result.jpg")
                try? FileManager.default.removeItem(at: keep)
                try FileManager.default.moveItem(at: r.finalURL, to: keep)
                return (keep, ["\(r.width)×\(r.height) output", "warnings: \(r.warnings)", "base: \(String(describing: r.lightingBaseIndex))", "contribution: \(r.lightingContribution)"])
            }.value
            result = ThumbnailService.image(for: url, maxPixel: 1400)
            log = lines.joined(separator: "\n") + String(format: "\nelapsed %.1f s", Date().timeIntervalSince(t0))
        } catch { log = "FAILED: \(error.localizedDescription)" }
        running = false
    }
}
